/**
 * Copyright (C) 2000-2014 Geometria Contributors
 * http://geocentral.net/geometria
 * 
 * Geometria is free software released under the MIT License
 * http://opensource.org/licenses/MIT
 */
var profile = {
    action: "release",
    releaseDir: "./release",
    mini: true,
    optimize: "closure",
    layerOptimize: "closure",
    cssOptimize: "comments",
    stripConsole: "none",
    selectorEngine: "lite",

    packages: [
        "dijit",
        "dojo",
        "dojox",
        
        "geometria"
    ],

    layers: {
        "dojo/dojo": {
            include: [
                "dijit/_base",
                "dijit/_base/manager",
                "dijit/CheckedMenuItem",
                "dijit/Dialog",
                "dijit/DropDownMenu",
                "dijit/MenuBar",
                "dijit/MenuItem",
                "dijit/MenuSeparator",
                "dijit/PopupMenuBarItem",
                "dijit/PopupMenuItem",
                "dijit/Toolbar",
                "dijit/ToolbarSeparator",
                "dijit/Tooltip",
                "dijit/TooltipDialog",
                "dijit/Tree",
                "dijit/form/_FormValueWidget",
                "dijit/form/Button",
                "dijit/form/ComboButton",
                "dijit/form/DropDownButton",
                "dijit/form/NumberTextBox",
                "dijit/form/SimpleTextarea",
                "dijit/form/ToggleButton",
                "dijit/form/ValidationTextBox",
                "dijit/layout/BorderContainer",
                "dijit/layout/ContentPane",
                "dijit/layout/LayoutContainer",
                "dijit/layout/TabContainer",
                "dijit/tree/dndSource",
                "dijit/tree/ObjectStoreModel",

                "dojo/_base/declare",
                "dojo/_base/lang",
                "dojo/aspect",
                "dojo/cookie",
                "dojo/Deferred",
                "dojo/domReady",
                "dojo/mouse",
                "dojo/request",
                "dojo/request/xhr",
                "dojo/data/ObjectStore",
                "dojo/dnd/AutoSource",
                "dojo/dnd/Target",
                "dojo/fx/Toggler",
                "dojo/store/Memory",
                "dojo/store/Observable",

                "dojox/grid/DataGrid",
                "dojox/widget/ColorPicker",
                "dojox/widget/Standby"
            ]
        },
        "geometria/geometria": {
            include: [
                "geometria/geometria",
                "geometria/GAnswerUtils",
                "geometria/GCalculation",
                "geometria/GCalculator",
                "geometria/GDictionary",
                "geometria/GFace",
                "geometria/GFigure",
                "geometria/GFigureMouseAdapter",
                "geometria/GFiguresContainer",
                "geometria/GGallery",
                "geometria/GHelp",
                "geometria/GHelpToolBar",
                "geometria/GLine",
                "geometria/GLogContainer",
                "geometria/GLogToolBar",
                "geometria/GMainContainer",
                "geometria/GMath",
                "geometria/GMeasurement",
                "geometria/GMenuBar",
                "geometria/GNavigator",
                "geometria/GNavigatorToolBar",
                "geometria/GNotepadContainer",
                "geometria/GNotepadRecord",
                "geometria/GPlaneConditions",
                "geometria/GPoint",
                "geometria/GProblem",
                "geometria/GProblemAnswer",
                "geometria/GProblemText",
                "geometria/GSegmentSetConditions",
                "geometria/GSolid",
                "geometria/GSolution",
                "geometria/GSolutionAnswer",
                "geometria/GToolBar",
                "geometria/GUtils",
                "geometria/GVariable",
                "geometria/GWidgets",

                "geometria/action/GActionBase",
                "geometria/action/GAnswerAction",
                "geometria/action/GAreaAction",
                "geometria/action/GBisectorAction",
                "geometria/action/GCalculateAction",
                "geometria/action/GDeselectAllAction",
                "geometria/action/GClearNotepadAction",
                "geometria/action/GCloneAction",
                "geometria/action/GColorAction",
                "geometria/action/GContentsAction",
                "geometria/action/GCubeAction",
                "geometria/action/GCutAction",
                "geometria/action/GDefaultAttitudeAction",
                "geometria/action/GRemoveFileAction",
                "geometria/action/GDivideSegmentAction",
                "geometria/action/GDivideAngleAction",
                "geometria/action/GDodecahedronAction",
                "geometria/action/GEraseSegmentAction",
                "geometria/action/GEraseSelectionAction",
                "geometria/action/GExitAction",
                "geometria/action/GExportDocumentAction",
                "geometria/action/GPrintFigureAction",
                "geometria/action/GFitToViewAction",
                "geometria/action/GHomePageAction",
                "geometria/action/GIcosahedronAction",
                "geometria/action/GImportDocumentAction",
                "geometria/action/GInitialAttitudeAction",
                "geometria/action/GIntersectionAction",
                "geometria/action/GJoinFiguresAction",
                "geometria/action/GJoinPointsAction",
                "geometria/action/GLabelsAction",
                "geometria/action/GLanguageAction",
                "geometria/action/GLayAngleAction",
                "geometria/action/GLayDistanceAction",
                "geometria/action/GLockProblemAction",
                "geometria/action/GLogCutAction",
                "geometria/action/GLogNextAction",
                "geometria/action/GLogRewindAction",
                "geometria/action/GLogStopAction",
                "geometria/action/GMeasureAngleAction",
                "geometria/action/GMeasureDistanceAction",
                "geometria/action/GMidpointAction",
                "geometria/action/GNavigatorAction",
                "geometria/action/GNewProblemAction",
                "geometria/action/GNewFolderAction",
                "geometria/action/GNextTopicAction",
                "geometria/action/GOctahedronAction",
                "geometria/action/GOpenAction",
                "geometria/action/GPerpendicularAction",
                "geometria/action/GPreviousTopicAction",
                "geometria/action/GPrismAction",
                "geometria/GProblemAnswer",
                "geometria/action/GPropertiesAction",
                "geometria/action/GPyramidAction",
                "geometria/action/GRedoAction",
                "geometria/action/GRemoveFigureAction",
                "geometria/action/GRenameFileAction",
                "geometria/action/GRenameFigureAction",
                "geometria/action/GRenamePointAction",
                "geometria/action/GRenameVariableAction",
                "geometria/action/GSaveDocumentAction",
                "geometria/action/GSaveDocumentAsAction",
                "geometria/action/GSaveFigureAction",
                "geometria/action/GScaleAction",
                "geometria/action/GSelectAllAction",
                "geometria/action/GSelectorAction",
                "geometria/action/GShearAction",
                "geometria/action/GSolveProblemAction",
                "geometria/action/GTetrahedronAction",
                "geometria/action/GTotalAreaAction",
                "geometria/action/GWireframeAction",
                "geometria/action/GUndoAction",
                "geometria/action/GHelpAction",
                "geometria/action/GVolumeAction",
                "geometria/action/GZoomInAction",
                "geometria/action/GZoomOutAction",

                "geometria/dictionary/dictionary-en",
                "geometria/dictionary/dictionary-es",

                "geometria/test/all",
                "geometria/test/math",
                "geometria/test/solid",
                "geometria/test/utils"
            ],
            customBase: true,
            boot: true
        }
    },

    resourceTags: {
        amd: function (filename, mid) {
            return /\.js$/.test(filename);
        }
    }
};
